[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
async-graphql = {  version = "7.0.11" }
sea-orm = "1.1.1"
bcrypt = "0.16.0"
validator = { version = "0.19.0", features = ["derive"] }
serde_json = "1.0.133"
indexmap = "2.6.0"